// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: multiplier.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type MultiplierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  string `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Second string `protobuf:"bytes,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *MultiplierRequest) Reset() {
	*x = MultiplierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplierRequest) ProtoMessage() {}

func (x *MultiplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiplier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplierRequest.ProtoReflect.Descriptor instead.
func (*MultiplierRequest) Descriptor() ([]byte, []int) {
	return file_multiplier_proto_rawDescGZIP(), []int{0}
}

func (x *MultiplierRequest) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *MultiplierRequest) GetSecond() string {
	if x != nil {
		return x.Second
	}
	return ""
}

// The response message containing the greetings
type MultiplierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MultiplierResponse) Reset() {
	*x = MultiplierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplierResponse) ProtoMessage() {}

func (x *MultiplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiplier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplierResponse.ProtoReflect.Descriptor instead.
func (*MultiplierResponse) Descriptor() ([]byte, []int) {
	return file_multiplier_proto_rawDescGZIP(), []int{1}
}

func (x *MultiplierResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *MultiplierResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_multiplier_proto protoreflect.FileDescriptor

var file_multiplier_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x41, 0x0a, 0x11, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x42, 0x0a,
	0x12, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x51, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12,
	0x43, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x67, 0x61, 0x63, 0x73, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiplier_proto_rawDescOnce sync.Once
	file_multiplier_proto_rawDescData = file_multiplier_proto_rawDesc
)

func file_multiplier_proto_rawDescGZIP() []byte {
	file_multiplier_proto_rawDescOnce.Do(func() {
		file_multiplier_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiplier_proto_rawDescData)
	})
	return file_multiplier_proto_rawDescData
}

var file_multiplier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiplier_proto_goTypes = []interface{}{
	(*MultiplierRequest)(nil),  // 0: protos.MultiplierRequest
	(*MultiplierResponse)(nil), // 1: protos.MultiplierResponse
}
var file_multiplier_proto_depIdxs = []int32{
	0, // 0: protos.Multiplier.Multiply:input_type -> protos.MultiplierRequest
	1, // 1: protos.Multiplier.Multiply:output_type -> protos.MultiplierResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiplier_proto_init() }
func file_multiplier_proto_init() {
	if File_multiplier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiplier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiplier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiplier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiplier_proto_goTypes,
		DependencyIndexes: file_multiplier_proto_depIdxs,
		MessageInfos:      file_multiplier_proto_msgTypes,
	}.Build()
	File_multiplier_proto = out.File
	file_multiplier_proto_rawDesc = nil
	file_multiplier_proto_goTypes = nil
	file_multiplier_proto_depIdxs = nil
}
